### ISSUE TITLE
[suggestion] Make runed portals respect FTBchunks claims/work like nether portals

### ISSUE THREAD

**Issue by theboo** [paulevsGitch/BetterEnd#99] opened 2021-02-19 20:31 UTC
Currently, if on a server, someone happens to have a base in the overworld at the coordinates where a runed portal in the end coincides, the portal will generate right inside their base when activated and destroy whatever they have there.

Would be good if there is some way to make them respect the claims from FTBchunks and place in the nearest available location. They should also probably look for a clear spot similar to nether portals rather than just plopping down in the exact location.

Might be cool to generate a small sky island where the portal gets placed. Would fit the theme i think.

Edit: looks like ftb chunks isnt ported to fabric quite yet(tho there is a PR ready to make this happen), i was suggested to make an issue here by the betterend forge maintainer:
https://github.com/Beethoven92/BetterEndForge/issues/58

**Comment by Beethoven92** [comment] 2021-02-19 20:35
I suggested you to open a request also here because this could be a nice enhancement to portals in general

**Comment by Beethoven92** [comment] 2021-02-23 22:20
I can confirm that Forge and Fabric use the same exact algorithms to generate the exit portal

**Comment by paulevsGitch** [comment] 2021-05-03 22:50
Looks like in new placement algorithm this shouldn't happen, so I'm closing this

**Closed by paulevsGitch** 2021-05-03 22:50 UTC
Labels: enhancement, suggestion
