### ISSUE TITLE
[Bug] Incompatibility with Lithium and C2ME

### ISSUE THREAD

**Issue by sorat0mo** [paulevsGitch/BetterEnd#419] opened 2022-01-23 14:29 UTC
Apart from C2ME, BetterEnd seems to be incompatible with Lithium. The log is as follows:

[crash-2022-01-22_00.38.22-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7920663/crash-2022-01-22_00.38.22-server.txt)

With BetterEnd and C2ME enabled, the server crashes when the End is first loaded. Subsequent crashes happen when going through end portal to outer islands.

With C2ME disabled but Lithium still up, the server crashes randomly seemingly when generating chunks.

BetterEnd seems to conflict with mods that modify the chunk generation logic, the server launches without crashing with BetterEnd disabled.

**Comment by paulevsGitch** [comment] 2022-01-24 19:16
Duplicate of #375

**Closed by paulevsGitch** 2022-01-24 19:16 UTC
