### ISSUE TITLE
Feature placement

### ISSUE THREAD

**Issue by w840306w** [paulevsGitch/BetterEnd#199] opened 2021-06-06 07:46 UTC
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2021/6/6 下午 3:15
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at net.minecraft.world.biome.source.BiomeArray.be_setBiome(BiomeArray:537)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiome(EndCaveFeature.java:155)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.lambda$place$0(TunelCaveFeature.java:135)
	at java.lang.Iterable.forEach(Unknown Source)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.place(TunelCaveFeature.java:109)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.generate(TunelCaveFeature.java:27)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55)
	at net.minecraft.world.gen.feature.DecoratedFeature.method_30384(DecoratedFeature:23)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
	at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:22)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:14)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55)
	at net.minecraft.world.biome.Biome.generateFeatureStep(Biome:373)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:220)
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89)
	at net.minecraft.world.chunk.ChunkStatus.mda111f8$lambda$injectLightmapSetup$1$4(ChunkStatus:1046)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Feature --
Details:
	Id: minecraft:decorated
	Config: < class_2986 [betterend:tunel_cave | [minecraft:count net.minecraft.class_2984@b2f097c]] >
	Description: < class_2988 [minecraft:decorated] >
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:376)
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806.mda111f8$lambda$injectLightmapSetup$1$4(class_2806.java:1046)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
-- Generation --
Details:
	CenterX: 44
	CenterZ: -109
	Seed: -1007587400291316291
	Biome: net.minecraft.class_1959@4a8a78e7
-- Chunk to be generated --
Details:
	Location: 44,-109
	Position hash: -468151435220
	Generator: net.minecraft.class_3754@11dbf04d
-- Affected level --
Details:
	All players: 1 total; [class_3222['SBC_R_CoCo'/44, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Chunk stats: ServerChunkCache: 2517
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-240,68,-224), Chunk: (at 0,4,0 in -15,-14; contains blocks -240,0,-224 to -225,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2067554 game time, 356794 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 10547 (now: false), thunder time: 78649 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 65030880 bytes (62 MB) / 800587776 bytes (763 MB) up to 2885681152 bytes (2752 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xmx3096M -Xms128M
	Suspected Mods: Better End (betterend)
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		adventurez: AdventureZ 1.2.2
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		betternether: Better Nether 5.0.7
		byg: BYG 1.1.8
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.1
		cavebiomes: Cave Biomes 0.6.2
		charm: Charm 2.3.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		croptopia: Croptopia 1.4.0
		dropz: Dropz 1.1.4
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.11.4
		ferritecore: FerriteCore 2.0.4
		go-fish: Go Fish 1.2.3-beta-1.16.5
		hydrogen: Hydrogen 0.2
		improved-stations: Improved Stations 2.0.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		minecraft: Minecraft 1.16.5
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		notenoughcrashes: Not Enough Crashes 3.2.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		phosphor: Phosphor 0.7.2+build.12
		rayon: Rayon 1.2.3
		rayon-core: Rayon Core API 1.2.3
		rayon-entity: Rayon Entity API 1.2.3
		rayon-particle: Rayon Particle API 1.2.3
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		roughlyenoughitems: Roughly Enough Items 5.12.235
		roughlyenoughitems-api: REI (API) 5.12.235
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.235
		roughlyenoughitems-runtime: REI (Runtime) 5.12.235
		stoneholm: Stoneholm 1.2.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		transporter: Transporter 1.0.3
		voyager: Voyager 1.0.0
		xaerominimap: Xaero's Minimap 21.9.0.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
	
****************** Not Enough Crashes Report ******************: 

 ConfiguredFeature Registry Name : Has no identifier as it was not registered... go yell at the mod owner when you find them! lol
 Biome Registry Name : minecraft:small_end_islands

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "betterend:tunel_cave"
    },
    "decorator": {
      "config": {
        "count": 1
      },
      "type": "minecraft:count"
    }
  },
  "type": "minecraft:decorated"
}

	Player Count: 1 / 20; [class_3222['SBC_R_CoCo'/44, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by paulevsGitch** [comment] 2021-06-06 10:42
Duplicate of #154, remove Hydrogen

**Closed by paulevsGitch** 2021-06-06 10:42 UTC
