### ISSUE TITLE
Crashing when travelling through End Gateway.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [paulevsGitch/BetterEnd#183] opened 2021-05-16 08:14 UTC
I travelled to the End to defeat the Ender Dragon. Afterward, I went through an End Gateway to explore the new biomes added by this mod only for it to crash the game before I could even go anywhere, which it seems to do consistently every time I touch the End Gateway. This is my most recent crash log as well as a screenshot of the crash occurring. Why is this happening?
![2021-05-16_03 06 45](https://user-images.githubusercontent.com/66750372/118390369-52c19c80-b5f4-11eb-8921-3483269b4e3b.png)
[crash-2021-05-16_03.06.06-server.txt](https://github.com/paulevsGitch/BetterEnd/files/6488865/crash-2021-05-16_03.06.06-server.txt)

**Comment by RDKRACZ** [comment] 2021-05-16 09:23
You are playing with Hydrogen mod which is incompatible with the current release of BE. The issue seems to be fixed in the development version, you can build it (instruction are in the readme file) or remove Hydrogen till official release. There is also a mod which should give you similar results to Hydrogen, it's possible it is compatible - I will test it now and edit this. - https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric

This is also a duplicate of https://github.com/paulevsGitch/BetterEnd/issues/154 and others

**Comment by Cookie-Kurokami** [comment] 2021-05-16 09:59
I previously played with both Hydrogen and Ferritecore simultaneously. Upon reading your message, I uninstalled Hydrogen and continued with Ferritecore. I can now confirm that Ferritecore is compatible with BetterEnd, and that you were right about Hydrogen being the cause of the issue. Thank you for your assistance, and sorry about the duplicate.
![2021-05-16_04 56 50](https://user-images.githubusercontent.com/66750372/118393190-64f70700-b603-11eb-8f7f-fc1a245e69df.png)

**Comment by paulevsGitch** [comment] 2021-05-16 14:54
Yes, this is a duplicate of #154, the issue was fixed in dev code from our side

**Closed by paulevsGitch** 2021-05-16 14:54 UTC
