### ISSUE TITLE
Game crashes whenever betterend chunks are loaded

### ISSUE THREAD

**Issue by DucksIncoming** [paulevsGitch/BetterEnd#175] opened 2021-05-13 23:38 UTC
Whether I use an end gate or just fly to the outer end islands the game crashes the moment any of those chunks are loaded. The main end island loads fine. Sorry if this is a duplicate issue I couldn't find anyone else asking about this.

Crash Report:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/13/21 7:34 PM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at net.minecraft.class_4548.be_setBiome(class_4548.java:537)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiome(EndCaveFeature.java:155)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.lambda$place$0(TunelCaveFeature.java:135)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature$$Lambda$8709/1445134437.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.place(TunelCaveFeature.java:109)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.method_13151(TunelCaveFeature.java:27)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_2988.method_30384(class_2988.java:23)
	at net.minecraft.class_2988$$Lambda$7581/1098494947.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_2988.method_12892(class_2988.java:22)
	at net.minecraft.class_2988.method_13151(class_2988.java:14)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_1959.method_8702(class_1959.java:373)
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$2089/1826242490.doWork(Unknown Source)
	at net.minecraft.class_2806.mdd06fd8$lambda$injectLightmapSetup$1$4(class_2806.java:1046)
	at net.minecraft.class_2806$$Lambda$2090/34284196.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$7418/1427010006.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$7415/1244138184.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$7358/1189033702.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4548.be_setBiome(class_4548.java:537)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiome(EndCaveFeature.java:155)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.lambda$place$0(TunelCaveFeature.java:135)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature$$Lambda$8709/1445134437.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.place(TunelCaveFeature.java:109)
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.method_13151(TunelCaveFeature.java:27)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)
	at net.minecraft.class_2988.method_30384(class_2988.java:23)
	at net.minecraft.class_2988$$Lambda$7581/1098494947.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.class_2988.method_12892(class_2988.java:22)
	at net.minecraft.class_2988.method_13151(class_2988.java:14)
	at net.minecraft.class_2975.method_12862(class_2975.java:55)

-- Feature --
Details:
	Id: minecraft:decorated
	Config: < class_2986 [betterend:tunel_cave | [minecraft:count net.minecraft.class_2984@bd34408]] >
	Description: < class_2988 [minecraft:decorated] >
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:373)

-- Generation --
Details:
	CenterX: 14
	CenterZ: 64
	Seed: -8177826593697258955
	Biome: net.minecraft.class_1959@611dae5f
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$2089/1826242490.doWork(Unknown Source)
	at net.minecraft.class_2806.mdd06fd8$lambda$injectLightmapSetup$1$4(class_2806.java:1046)
	at net.minecraft.class_2806$$Lambda$2090/34284196.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: 14,64
	Position hash: 274877906958
	Generator: net.minecraft.class_3754@1c46be11
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$7418/1427010006.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$7415/1244138184.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$7358/1189033702.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)

-- Affected level --
Details:
	All players: 1 total; [class_3222['DucksIncoming'/158, l='ServerLevel[Yeetcraft 3.0]', x=52.17, y=102.82, z=853.83]]
	Chunk stats: ServerChunkCache: 2085
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-240,80,48), Chunk: (at 0,5,0 in -15,3; contains blocks -240,0,48 to -225,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9638 game time, 9638 day time
	Level name: Yeetcraft 3.0
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 153659 (now: false), thunder time: 106087 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:874)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7237/1692823245.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 653720472 bytes (623 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		beebetter: Bee Better 1.8.0-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		bewitchment: Bewitchment 1.16.5-12
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		bno: Basic Nether Ores 1.16.5-5.5.0-Fabric
		bookworm: Bookworm Library 3.1.0
		byg: BYG 1.1.7
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cavebiomes: Cave Biomes 0.6.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.24
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		commonformatting: common formatting 1.0.1
		croptopia: Croptopia 1.3.5
		crowdin-translate: CrowdinTranslate 1.2
		customportalapi: Custom Portals 0.0.1-beta29-1.16
		dynamicentry: dynamic entry 0.1.3
		dynmus: Dynamic Music 1.1.0
		enchant_giver: Enchant Giver 1.0.3
		endlessoceans: Endless Oceans 1.0.0
		enhancedcelestials: Enhanced Celestials 1.0.2
		entityculling: EntityCulling-Fabric 1.2.2
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricasmtools: Fabric ASM tools 0.3.2
		fabricloader: Fabric Loader 0.11.3
		fasttransferlib: Fast Transfer Lib 0.3.1
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.4.2-1.16.5
		geckolib3: Geckolib 3.0.34
		go-fish: Go Fish 1.2.1-beta-1.16.4
		grossfabrichacks: GrossFabricHacks 1.1.0
		hydrogen: Hydrogen 0.2
		illuminations: Illuminations 1.5.1
		impersonate: Impersonate 2.2.1
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.9.9-BETA
		inventoryhud: Inventory HUD + 3.3.0
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		libstructure: LibStructure 1.5
		limitless: limitless 1.1.4
		lithium: Lithium 0.6.4
		magna: Magna 0.2.1-1.16.5
		mcdw: MC Dungeons Weapons 3.1.2
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.9
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		net_bytebuddy_byte-buddy-agent: byte-buddy-agent 1.10.20
		net_gudenau_lib_unsafe: unsafe 1.4.1
		nourish: Nourish 1.2.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		phormat: phormat 1.0.0
		phosphor: Phosphor 0.7.2+build.12
		playerabilitylib: Pal 1.2.1
		ratsmischief: Rat's Mischief 1.1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		seedy-behavior: Seedy Behavior 1.0.1
		sodium: Sodium 0.1.0
		somnus: Somnus API 0.0.11-1.16.5
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.3
		terraform-config-api-v1: Terraform Config API (v1) 1.0.2
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.2
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.2
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.3
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		the_aether: The Aether 1.16.5-1.0.3
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		user11681_reflect: reflect 1.3.0
		user11681_shortcode: shortcode 0.4.0
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		xlpackets: XLPackets 1.1
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['DucksIncoming'/158, l='ServerLevel[Yeetcraft 3.0]', x=52.17, y=102.82, z=853.83]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by paulevsGitch** [comment] 2021-05-14 07:34
Duplicate of #154 - remove Hydrogen

**Closed by paulevsGitch** 2021-05-14 07:34 UTC
