### ISSUE TITLE
Crash when entering the End

### ISSUE THREAD

**Issue by DaisukeVN** [paulevsGitch/BetterEnd#190] opened 2021-05-27 18:28 UTC
Using newest Release Version of BetterEnd & newest Fabric Version
Server & Client crashing...
```
[12:57:25] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_261]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_261]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:579) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_261]
	... 11 more
Caused by: java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6) ~[?:?]
	at net.minecraft.world.biome.source.BiomeArray.be_setBiome(BiomeArray:537) ~[?:?]
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiome(EndCaveFeature.java:155) ~[betterend.jar:?]
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.lambda$place$0(TunelCaveFeature.java:135) ~[betterend.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_261]
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.place(TunelCaveFeature.java:109) ~[betterend.jar:?]
	at ru.betterend.world.features.terrain.caves.TunelCaveFeature.generate(TunelCaveFeature.java:27) ~[betterend.jar:?]
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.method_30384(DecoratedFeature:23) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_261]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_261]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_261]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_261]
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:22) ~[?:?]
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:14) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55) ~[?:?]
	at net.minecraft.world.biome.Biome.generateFeatureStep(Biome:373) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:220) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.md72bd7c$lambda$injectLightmapSetup$1$4(ChunkStatus:1046) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-minecraft_server.1.16.5.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_261]
	... 11 more
```

**Comment by paulevsGitch** [comment] 2021-05-27 19:58
Looks like duplicate of #154, do you have Hydrogen?

**Comment by paulevsGitch** [comment] 2021-05-27 20:34
Looks like yes

**Closed by paulevsGitch** 2021-05-27 20:34 UTC
Labels: question
