### ISSUE TITLE
Chunky cannot preload the end with BetterEnd installed.

### ISSUE THREAD

**Issue by TheTennessee** [paulevsGitch/BetterEnd#425] opened 2022-01-31 00:01 UTC
So, I have been trying to preload the end in order to prepare my server for a few players. I am using a mod called Chunky to do so. Chunky essentially just loads up new chunks as a constant process. When I ran it on the overworld and the nether (with betternether installed) no problems. Loading it on the end (with BetterEnd installed) causes the progress to stall, and the server sometimes won't shut down properly (being stuck in a constant saving mode). I've tried on single player to similar results, and I have tried to fly through the end loading chunks manually only to have things stall out there as well (chunk loading stops, and I fly to an edge of unloaded chunks that never continues). So it isn't just chunky.

I have tested without BetterEnd installed, and received no issues. I re-installed BetterEnd, and uninstalled RepurposedStructures (the only other mod that could have been touching the end dimension's chunk loading), and I still got the same error in Chunky. So it seems to be coming from BetterEnd.

I am using minecraft 1.18.1, with the latest version of BClib and BetterEnd. I also have no problems with BetterNether.

Here's the error I got most recently during the BetterEnd on RepurposedStructures mod off run:

```
[17:28:57] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 3 chunks (0.00%), ETA: 0:59:08, Rate: 17.8 cps, Current: 1, -1
[17:28:58] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 133 chunks (0.21%), ETA: 0:09:14, Rate: 113.3 cps, Current: 6, -6
[17:28:59] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 347 chunks (0.55%), ETA: 0:06:37, Rate: 157.5 cps, Current: -5, 9
[17:29:00] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 561 chunks (0.89%), ETA: 0:05:56, Rate: 175.1 cps, Current: 4, -12
[17:29:01] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 741 chunks (1.18%), ETA: 0:05:53, Rate: 176.3 cps, Current: 14, 2
[17:29:01] [IO-Worker-31/ERROR]: Failed to store chunk [13, 16]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10631(class_2507.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10628(class_2507.java:83) ~[server-intermediary.jar:?]
	at net.minecraft.class_2867.method_23726(class_2867.java:79) ~[server-intermediary.jar:?]
	at net.minecraft.class_4698.method_23701(class_4698.java:174) ~[server-intermediary.jar:?]
	at net.minecraft.class_4698.method_23719(class_4698.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:59) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [server-intermediary.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:29:02] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 844 chunks (1.34%), ETA: 0:06:24, Rate: 161.6 cps, Current: 15, 12
[17:29:03] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 913 chunks (1.45%), ETA: 0:07:04, Rate: 146.4 cps, Current: -15, -3
[17:29:06] [IO-Worker-29/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[17:29:06] [IO-Worker-29/WARN]: Failed to read chunk [13, 16]
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:75) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10627(class_2507.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_2867.method_17911(class_2867.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_4698.method_27943(class_4698.java:100) ~[server-intermediary.jar:?]
	at net.minecraft.class_4698.method_27939(class_4698.java:150) ~[server-intermediary.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:59) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [server-intermediary.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:273) ~[?:?]
	at net.minecraft.class_2487.method_10542(class_2487.java:480) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:131) ~[server-intermediary.jar:?]
	... 12 more
[17:29:06] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3932ms or 78 ticks behind
[17:29:07] [Server thread/INFO]: [Chunky] Task running for minecraft:the_end. Processed: 1036 chunks (1.64%), ETA: 0:09:56, Rate: 103.9 cps, Current: -16, -5
```
[latest(1).log](https://github.com/paulevsGitch/BetterEnd/files/7967245/latest.1.log)

**Comment by quiqueck** [comment] 2022-02-04 08:55
This may be a duplicate of #394

**Comment by quiqueck** [comment] 2022-02-04 14:14
Could you please try again with the just release 1.0.2-Version?

**Comment by TheTennessee** [comment] 2022-02-04 21:12
So far it is looking good. If it is a duplicate, and it's the sulfur lake that is the cause, then I can confirm in singleplayer I explored for a while and ran upon a sulfur lake and it worked fine.

I am going to run it server side, but it'll take a few hours before I know for certain. Thank you for getting to this, and the lakes look pretty awesome. ^_^

**Comment by TheTennessee** [comment] 2022-02-05 00:36
Well, after getting chunky to load out to a 5000 block radius, I am going to say this is fixed. I couldn't get past 2000 blocks before this.

**Comment by quiqueck** [comment] 2022-02-05 14:02
Thanks for reporting back. I will close this issue for now. Please report back to us if the problem returns.

**Closed by quiqueck** 2022-02-05 14:02 UTC
Labels: bug, question
