### ISSUE TITLE
REI recpies missing

### ISSUE THREAD

**Issue by MJRamon** [paulevsGitch/BetterEnd#404] opened 2022-01-12 12:16 UTC
Not all item recipes are shown in REI. For example, thallassium_forged_plate, therminite_forged_plate, aeternium_forged_plate, thallasium_sword_blade and so on.

**Comment by paulevsGitch** [comment] 2022-01-12 12:20
Duplicate of #389 and #384

**Closed by paulevsGitch** 2022-01-12 12:20 UTC
