### ISSUE TITLE
Crash upon trying to enter Worldblender world with Allure

### ISSUE THREAD

**Issue by defenestrationdude** [paulevsGitch/BetterEnd#37] opened 2020-12-21 20:31 UTC
[crash-2020-12-21_05.49.09-server.txt](https://github.com/paulevsGitch/BetterEnd/files/5726343/crash-2020-12-21_05.49.09-server.txt)
I'm not sure which of these mods is responsible exactly; entering the end normally without World Blender seemed to work (although i didn't explore all of the biomes added from Better End), but the crash report mentions Allure.

**Comment by paulevsGitch** [comment] 2020-12-21 22:41
Hi, this is known issue with Allure Speleothem block (the same issue happened in BetterNether)
What actually happens:
- Some features from BetterEnd use simple function to cleanup wrong placed blocks (for example lakes use this method to remove floating plants (in the air);
- This function calls method **canPlace** from block class, using **WorldAccess** (actually, **StructureWorldAccess**) as first parameter;
- Inside the Allure block there is a function that accepts only **World** (_class_1937_), but it get **ChunkRegion** (_class_3233_, instance of **StructureWorldAccess**), and couldn't handle it (in **SpeleothemBlock**, line 51), this results as crash you get.

Actually, the problem is mostly on Allure side. I can make a simple solution - try to ignore Allure blocks, but this will make code extremely slow as I will need to call block registry on each block test. It will be perfect if it will be fixed from Allure side, you can try to post this issue on Allure mod issues with my comment.

From my siede this function can't be disabled - it fix many terrain generator issues, that happens in chunks on generation process with big features - floating plants, sand blocks, partly destroyed chorus plants, unupdated water blocks and other things

**Closed** 2020-12-27 13:40 UTC
Labels: bug, compatibility, external problem
