### ISSUE TITLE
BetterEnd spams console with exceptions

### ISSUE THREAD

**Issue by PaulZappia** [paulevsGitch/BetterEnd#243] opened 2021-07-13 12:36 UTC
When I boot up my modded MC instance with BetterEnd, it floods the console with exceptions.
Here's a log: https://drive.google.com/file/d/1S4LRa_NqsLJCqOdIsHfp2I3J_y9CBU63/view?usp=sharing

**Comment by PaulZappia** [comment] 2021-07-13 13:07
Ah, I see. I'll try getting rid of Dimensional Doors and updating BetterEnd and see if that fixes the issue.

**Comment by PaulZappia** [comment] 2021-07-13 13:30
Just updated the mod and tried booting the game up and now I've got a new problem. When loading into the game, it just can't get past the Mojang screen. It gets to the end, starts fading into the title screen but jumps right back to the Mojang screen. Plus, all the symbols on the title screen are the same. 
Here's a video: https://drive.google.com/file/d/1ILYfLaDPdZOzwtfCUK4gi7k0LLn2gp-N/view?usp=sharing

Btw, running the game without the mod still works just fine.

**Comment by paulevsGitch** [comment] 2021-07-13 19:22
The issue is the same as #244 and #241

**Comment by paulevsGitch** [comment] 2021-07-18 11:11
As this is external problem (outside of BE compat) I'm closing this

**Closed by paulevsGitch** 2021-07-18 11:11 UTC
Labels: external problem
