### ISSUE TITLE
BetterEnd seems to be causing a "connection lost" error.

### ISSUE THREAD

**Issue by heyjudek** [paulevsGitch/BetterEnd#188] opened 2021-05-25 16:09 UTC
Here's the log of the crash. A minute into loading the game, I receive a message that BetterEnd is likely the cause of the crash.
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6540773/latest.log)

**Comment by heyjudek** [comment] 2021-05-25 17:01
Here's the very latest one with the crash report
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6541048/latest.log)
[crash-2021-05-25_18.55.30-server.txt](https://github.com/paulevsGitch/BetterEnd/files/6541051/crash-2021-05-25_18.55.30-server.txt)

**Comment by paulevsGitch** [comment] 2021-05-25 18:30
Duplicate of #154, disable Hydrogen mod

**Closed by paulevsGitch** 2021-05-25 18:30 UTC

**Comment by heyjudek** [comment] 2021-05-25 18:53
I figured it out, it didn't have to do with Hydrogen but "Fast leaf decay". Getting rid of it fixed the issue.
