### ISSUE TITLE
End stone texture error

### ISSUE THREAD

**Issue by tuananhlqpro** [paulevsGitch/BetterEnd#415] opened 2022-01-21 08:54 UTC
Hi! I added Better End 0.12.5-minecraft 1.17.1 and BCLib 0.5.6 to my modpack. When I create a new world and go to the end, everything is working fine but endstone textures pack is error. Can you fix it? 
Here is my modlist: https://pastebin.com/WLFeCcZk

**Comment by paulevsGitch** [comment] 2022-01-21 09:17
Can you please give more specific information? Log output, screenshots?

**Comment by tuananhlqpro** [comment] 2022-01-21 09:31
log output here: https://paste.gg/p/anonymous/7605e3341fb645db922b9ebea54b4a26

**Comment by tuananhlqpro** [comment] 2022-01-21 09:38
![2022-01-21_15 15 25](https://user-images.githubusercontent.com/98151259/150503611-cf0f40d7-9963-40ab-bdc8-341452441b96.png)

**Comment by tuananhlqpro** [comment] 2022-01-21 09:44
![2022-01-21_16 43 07](https://user-images.githubusercontent.com/98151259/150504496-45f57d73-915c-4940-bab4-68b7f7825b6e.png)

**Comment by paulevsGitch** [comment] 2022-01-21 10:28
Duplicate of #400

**Closed by paulevsGitch** 2022-01-21 10:28 UTC
Labels: question

**Comment by tuananhlqpro** [comment] 2022-01-21 10:47
thank you! i fixed it
