### ISSUE TITLE
Going into a unmodded server with the mod enabled makes blocks look entiriely different 

### ISSUE THREAD

**Issue by ObsidianOS7** [paulevsGitch/BetterEnd#178] opened 2021-05-15 15:22 UTC
Purpur Server with no mod on client side
![2021-05-15_09 13 50](https://user-images.githubusercontent.com/71942224/118367025-ed22d100-b55d-11eb-88d9-c34fc9608207.png)
Purpur Server with mod on client side
![2021-05-15_09 16 34](https://user-images.githubusercontent.com/71942224/118367395-42f77900-b55e-11eb-9825-9a1160d5c9d3.png)

This is an issue with users who play on both my server that is unmodded and also play on my modded server.

**Comment by paulevsGitch** [comment] 2021-05-15 19:58
Duplicate of #49. You can disable chorus plant modification in configs but this will affect modded servers and world. The mod is not designed to be used on client-side on unmodded servers

**Closed by paulevsGitch** 2021-05-15 19:58 UTC

**Comment by IAm2TheDude** [comment] 2021-06-01 03:34
Question, if the mod is working correctly on the server and on client side, this form of corruption won't happen right? And if someone somehow loaded the server without the mod (idk if that's possible in any way I'm just scared.) there would be no way that they could corrupt the server right? Just a bit worried about this mod as other mods were working and then it got corrupted, and I don't want my server corrupted. I can probably just make a copy of the world or something but still.

**Comment by paulevsGitch** [comment] 2021-06-01 03:50
This bug is not world corruption, it is only a visual glitch - Minecraft send blockstates as a set of long numbers from server to client without checking if this blockstate is from this block or not, as a result if mod is installed on client and not installed on server - it will cause blocks to change their appearance for the client (all logic is on server side, that's why it is only visual bug). If you have mod on both server and client with same config - you will never see this issue.

The reason why vanilla blocks have this effect too with BE is Chorus plant modification - additional blockstates adds more blockstate numbers and offsets all other blockstates in registry. Disabling chorus additional state in the config will fix this bug, but chorus plants will probably not work correctly in modded worlds
