### ISSUE TITLE
Anvil Recipes eat the ingredients in Multiplayer

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#308] opened 2021-09-15 20:46 UTC
The anvil recipes are just fine in singleplayer, but in multiplayer, they eat the ingredients! The hammer just despawns out of your inventory instead of taking damage!

**Comment by paulevsGitch** [comment] 2021-09-15 22:23
Duplicate of #291

**Closed by paulevsGitch** 2021-09-15 22:23 UTC
