### ISSUE TITLE
All the Fabric 3 Ender Dragon wont respawn

### ISSUE THREAD

**Issue by ErickSann** [paulevsGitch/BetterEnd#364] opened 2021-12-07 11:22 UTC
while playing on my server with friends we killed the ender dragon but tried to respawn it to get dragons breath for items to craft however trying to respawn it the vanilla way but that wasn't working if there is a different way to respawn the dragon could anyone let me know

**Comment by paulevsGitch** [comment] 2021-12-07 11:41
Additional information is required:
1. What mod version are you using
2. What MC version are you using
3. What are in logs?
4. Are you on client or on server

**Comment by ErickSann** [comment] 2021-12-07 18:21
1. Yes im on the version 2.8.7 of all the fabric 3 
2. The mod pack is running 1.16.5 
3. dont really know what to be looking for in the logs 
4. and im on a server

**Comment by paulevsGitch** [comment] 2021-12-08 05:57
1. Not modpack version, mod version
2. Versions for MC 1.16.5 are outdated and are not supported anymore
3. logs are in minecraft/logs, identical on client and server
4. This bug is related to server file access. In 1.17+ there is another system that is not related to server file access anymore

**Comment by paulevsGitch** [comment] 2021-12-08 07:50
Duplicate of old and closed issues

**Closed by paulevsGitch** 2021-12-08 07:50 UTC
Labels: question
