### ISSUE TITLE
My game crashed when I entering end gateway

### ISSUE THREAD

**Issue by DeeChael** [paulevsGitch/BetterEnd#169] opened 2021-05-09 06:06 UTC
I don't know why
This is my game log:
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6447006/latest.log)
And this is my crash report:
[crash-2021-05-09_13.09.41-server.txt](https://github.com/paulevsGitch/BetterEnd/files/6447007/crash-2021-05-09_13.09.41-server.txt)

**Comment by paulevsGitch** [comment] 2021-05-09 07:14
Looks like duplicate of #154, try to remove hydrogen

**Closed** 2021-05-09 07:35 UTC
