### ISSUE TITLE
Forging Terminite Ingots into plates

### ISSUE THREAD

**Issue by alextoddslick** [paulevsGitch/BetterEnd#324] opened 2021-10-16 17:04 UTC
There is a server issue when if you have all the configs and mods synced up it will give you one of the item you are forging and delete your tool used to forge the item. I have tried this on many throw up servers now and it seems that it is only an issue for the server instances. This is on 1.17.1 and here are the mods

architectury-2.5.32.jar
bclib-0.3.1.jar
better-end-0.11.0-pre.jar
Chunky-1.2.124.jar
fabric-api-0.40.8+1.17.jar
modmenu-2.0.9.jar

**Comment by paulevsGitch** [comment] 2021-10-16 17:21
Duplicate of #291

**Closed by paulevsGitch** 2021-10-16 17:21 UTC

**Comment by paulevsGitch** [comment] 2021-10-16 17:27
No, fix will require update of both BCLib & BE, this will require some time. You can make a custom datapack to avoid item loss on your server

**Comment by alextoddslick** [comment] 2021-10-16 23:36
Could you outline what would need to be done in order to fix this??? I am not exactly "great" with java.
