### ISSUE TITLE
Crash at world creation (Terralith + Terrablender)

### ISSUE THREAD

**Issue by charmesal** [paulevsGitch/BetterEnd#426] opened 2022-02-01 02:58 UTC
This issue seemed similar to [380](https://github.com/paulevsGitch/BetterEnd/issues/380) but the logs are different enough so I decided to create a new issue.

I'm using the latest version of all mods (Fabric API, Terralith, Terrablender, BetterEnd, BetterNether, BCLib

The problem seems to exists with Terralith and BetterEnd/BetterNether but only when Terrablend is also loaded. Without it it runs fine. But Terrablend and Terralith work fine without BetterEnd/BetterNether.
Here a little overview for people who prefer their data visualized https://imgur.com/a/PNL8Wa6

[latest.log](https://pastebin.com/pScJXp3G)
[crash report](https://pastebin.com/uJ5WAsMC)

**Comment by charmesal** [comment] 2022-02-02 02:08
I just came across [issue 22](https://github.com/Glitchfiend/TerraBlender/issues/22) on the TerraBlender Github which is this exact issue.
As you guys are already aware of it and working on it you can close this issue. Or keep it open as a reminder/indication for others so they know the issue is known to you guys.

**Comment by itsdinkd** [comment] 2022-02-02 03:20
I'm running all that you mentioned just fine.

**Comment by JDtheHutt** [comment] 2022-02-02 10:39
I was just gathering mine for the same report, I see exactly the same result.  Terralith with Terrablender and BetterNether and/or BetterEnd crashes on worldgen.  Terralith with just BetterNether and/or BetterEnd works fine.  Terralith with Terrablender and any other overworld biome mod works fine.  It is only when Terrablender is included with BetterEnd or BetterNether.  Tried mine across 2 different Linux distros (Ubuntu 21.10 and PopOS 21.10 though Pop is also Ubuntu based) on 3 entirely different hardware platforms, and with both the official MC launcher and using GD Launcher, using both system installed Java and the GD Launcher built-in Java.  I will add logs in a minute but they look the same.

**Comment by charmesal** [comment] 2022-02-02 14:16
> I'm running all that you mentioned just fine.

Can you post your modlist?
This is a known issue and maybe you're running other versions that are more compatible

**Comment by charmesal** [comment] 2022-02-02 14:18
> I was just gathering mine for the same report, I see exactly the same result. Terralith with Terrablender and BetterNether and/or BetterEnd crashes on worldgen. Terralith with just BetterNether and/or BetterEnd works fine. Terralith with Terrablender and any other overworld biome mod works fine. It is only when Terrablender is included with BetterEnd or BetterNether. Tried mine across 2 different Linux distros (Ubuntu 21.10 and PopOS 21.10 though Pop is also Ubuntu based) on 3 entirely different hardware platforms, and with both the official MC launcher and using GD Launcher, using both system installed Java and the GD Launcher built-in Java. I will add logs in a minute but they look the same.
> 
> There is this currently open ticket on the Terrablender github which I assumed related but speaking to paulevs on Discord, it was thought this should now work. [Glitchfiend/TerraBlender#22](https://github.com/Glitchfiend/TerraBlender/issues/22)
> 
> My logs:
> 
> latest.log: https://pastebin.com/dqBNVGaw crash report: https://pastebin.com/GHpewvfA

You said it should now work but I see no updates for any of the mods so I don't see how it's fixed for us. Am I missing something?

**Comment by JDtheHutt** [comment] 2022-02-02 14:22
> You said it should now work but I see no updates for any of the mods so I don't see how it's fixed for us. Am I missing something?

It was the developer who said that in Discord when I spoke with them, that it should work if you load the world twice.  However, mine is crashing when the world gen starts and no world able to be loaded a second time, so not able to do that.

**Comment by charmesal** [comment] 2022-02-02 15:11
> > You said it should now work but I see no updates for any of the mods so I don't see how it's fixed for us. Am I missing something?
> 
> It was the developer who said that in Discord when I spoke with them, that it should work if you load the world twice. However, mine is crashing when the world gen starts and no world able to be loaded a second time, so not able to do that.

Same here. There is no world as it crashes on creation.
Creating a world without Terralith, deleting the region folder in the save folder, and then adding the Terralith datapack seems to world though. It seems to generate the same world but replacing some (parts of) biomes with Terralith biomes. Which is fine and dandy. I think I'll just go with this solution as I'll generate one world for a multiplayer server so I won't have to keep doing this over and over.

**Comment by itsdinkd** [comment] 2022-02-03 21:52
Apologies, you mentioned "World Creation". It didn't happen to me when I joined a pre-existing world not created with TerraBlender. I crashed on creation.

**Comment by itsdinkd** [comment] 2022-02-03 21:55
> > > You said it should now work but I see no updates for any of the mods so I don't see how it's fixed for us. Am I missing something?
> > 
> > 
> > It was the developer who said that in Discord when I spoke with them, that it should work if you load the world twice. However, mine is crashing when the world gen starts and no world able to be loaded a second time, so not able to do that.
> 
> Same here. There is no world as it crashes on creation. Creating a world without Terralith, deleting the region folder in the save folder, and then adding the Terralith datapack seems to world though. It seems to generate the same world but replacing some (parts of) biomes with Terralith biomes. Which is fine and dandy. I think I'll just go with this solution as I'll generate one world for a multiplayer server so I won't have to keep doing this over and over.

If this works when you use Terralith as a datapack, and not a mod, the incompatibility is due to terralith's dependency it uses, Seedfix. I suggest bringing this to Terralith.

**Comment by TheButterbrotMan** [comment] 2022-02-03 23:28
https://bytebin.lucko.me/Vxr9TdHV4l

**Comment by JDtheHutt** [comment] 2022-02-03 23:35
> If this works when you use Terralith as a datapack, and not a mod, the incompatibility is due to terralith's dependency it uses, Seedfix. I suggest bringing this to Terralith.

This happens to me when added as the mod from their curseforge page.

**Comment by quiqueck** [comment] 2022-02-04 08:52
duplicate of paulevsGitch/BetterNether#503

**Comment by quiqueck** [comment] 2022-02-04 08:53
Terralith alone does work fine (at least I am testing with it and so far had no problems with it). TerraBlender on the other hand is causing issues, that will be fixed in the next release.

**Comment by quiqueck** [comment] 2022-02-04 14:14
The fix for this should be in 1.0.2. Please reopen this issue if you still have the same problem after upgrading. An please note that while the crash is fixed. TerraBlender and BetterEnd are still not compatible. You can track our progress in that regard here paulevsGitch/BetterNether#504  and here Glitchfiend/TerraBlender#22

**Closed by quiqueck** 2022-02-04 14:14 UTC

**Comment by charmesal** [comment] 2022-02-04 17:36
> Terralith alone does work fine (at least I am testing with it and so far had no problems with it). TerraBlender on the other hand is causing issues, that will be fixed in the next release.

Weird because TerraBlender and BetterEnd/BetterNether work fine together. (besides the other known issue of BetterNether not spawning any nether biomes.) It's only when adding the Terralith mod that it crashes.

> The fix for this should be in 1.0.2. Please reopen this issue if you still have the same problem after upgrading. An please note that while the crash is fixed. TerraBlender and BetterEnd are still not compatible. You can track our progress in that regard here [paulevsGitch/BetterNether#504](https://github.com/paulevsGitch/BetterNether/issues/504) and here [Glitchfiend/TerraBlender#22](https://github.com/Glitchfiend/TerraBlender/issues/22)

If the 1.0.2 update fixes the crash but nothing else than that's at least good on that note. I'll keep an eye on your progress and hope both teams can work something out. In the meantime I think we can live with a normal nether. Or people can use a nether overhaul datapack which seems to work fine.

**Comment by itsdinkd** [comment] 2022-02-09 01:40
> > If this works when you use Terralith as a datapack, and not a mod, the incompatibility is due to terralith's dependency it uses, Seedfix. I suggest bringing this to Terralith.
> 
> This happens to me when added as the mod from their curseforge page.

Yes. The mod has SeedFix in it

**Comment by itsdinkd** [comment] 2022-02-09 01:43
The problem is clearly SeedFix guys.
