### ISSUE TITLE
Issues with resurrecting the Ender Dragon

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#149] opened 2021-04-29 22:00 UTC
The changes to the End exit portal and pillars have created some issues.
- Resurrecting the Ender Dragon is now impossible in survival mode, as none of the bedrock blocks upon which the End crystals can be placed are recognised. In creative or with commands, the player can replace some of the portal blocks with bedrock blocks in the positions that they would be in in vanilla, and then place the crystals on those to resurrect the dragon.
Here is a portal with numerous crystals placed on it, none of which can resurrect the dragon:
![2021-04-29_14 56 08](https://user-images.githubusercontent.com/69029346/116623558-47375b80-a8fb-11eb-927c-82ec70a56d1d.png)
Placing bedrock blocks where they would be in vanilla and placing the crystals on them works:
![2021-04-29_14 58 31](https://user-images.githubusercontent.com/69029346/116623656-6d5cfb80-a8fb-11eb-844e-12464b0ac39b.png)

- The pillars sometimes clear large areas around their bases when reconstructed by the resurrection sequence.
In this picture, note the large square holes:
![2021-04-29_14 51 46](https://user-images.githubusercontent.com/69029346/116623774-98dfe600-a8fb-11eb-9cbd-1bff728dc1ef.png)

**Comment by paulevsGitch** [comment] 2021-05-03 20:38
Empty areas around pillars is a vanilla mechanics of pillar regeneration, in normal casae they clear area around crystal. I fixed pillar height calculations and now they will work as intended. I also fixed crystal positions on new portal - it will require 4 crystals on the same 4 directions

**Comment by paulevsGitch** [comment] 2021-05-06 21:34
Fixed in 0.9.5

**Closed by paulevsGitch** 2021-05-06 21:34 UTC
Labels: bug, enhancement, in dev code

**Comment by irunatbullets** [comment] 2021-07-23 20:16
I'm not sure how what to do here. On both the NA and EU AOF3 servers which are using better-end-0.9.8.5-pre, players can't resurrect the dragon.

I have tried reseting the regions and deleting the betterend file from world/data/ - which works the first time but the dragon is there because it's reset - not through summoning.

I have also tried changing the placement of the crystals as mentioned above
![image](https://user-images.githubusercontent.com/344908/126836370-51918d92-0648-4a26-a589-59a73818713f.png)

But I can't seem to be able to figure out how to resurrect this thing.

**Comment by paulevsGitch** [comment] 2021-07-23 20:33
0.9.8.5 is outdated version, dragon spawning on server use different code and it will be not fixed for 1.16.5 (as the main version is 1.17.1 now and this bug was discovered on it). You can disable custom portal & pillars in the generator.json and regenerate central island - all dragon spawning will have vanilla behaviour, this should solve the problem for you

**Comment by irunatbullets** [comment] 2021-07-23 21:26
Ah, I misread the version number. I'll give this a go. Thank you.
