### ISSUE TITLE
Crash while attempting to generate Sulphuric Lake

### ISSUE THREAD

**Issue by liamrwilkins** [paulevsGitch/BetterEnd#394] opened 2022-01-08 00:57 UTC
The end was running really well until my game hard crashed on structure placement. 

Crash Log is attached. I was running a LAN server while playing in singleplayer (to enable cheats).

[crash-2022-01-07_19.51.37-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7832060/crash-2022-01-07_19.51.37-server.txt)

**Comment by paulevsGitch** [comment] 2022-01-08 01:21
Can you please also attach latest game logs?

**Comment by liamrwilkins** [comment] 2022-01-08 01:34
Sure, here they are. 
I loaded up the same again and it didn't hard crash the second time. It did soft crash after a few minutes though (all entities froze, and no new chunks would load. When I tried to relog, the game was stuck on the "Saving world" screen).

[rei.log](https://github.com/paulevsGitch/BetterEnd/files/7832147/rei.log)
[2022-01-07-1.log.gz](https://github.com/paulevsGitch/BetterEnd/files/7832148/2022-01-07-1.log.gz)
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/7832149/latest.log)

**Comment by quiqueck** [comment] 2022-01-19 21:45
Could you please try with the latest bclib/betterend. The issue may have been fixed with that bclib updated (at least I can not reproduce it with the current version)

**Comment by LeafWDM** [comment] 2022-01-26 19:06
> Could you please try with the latest bclib/betterend. The issue may have been fixed with that bclib updated (at least I can not reproduce it with the current version)

It has not been fixed. I am still having this issue.

**Comment by quiqueck** [comment] 2022-01-27 12:08
Thanks for getting back. Could you please send us the world seed and maybe the coordinates of the biome that is causing the issue.

**Comment by cypressfalls** [comment] 2022-01-28 02:28
On my world, the seed is 8624896 and the coordinates causing problems are centralized around 695 112 -1984. We were allowed to explore it for probably 10 minutes before it overloaded and crashed everything.

**Comment by liamrwilkins** [comment] 2022-01-28 15:35
For what it's worth, the issue has not occurred again in my world since updating!

**Comment by quiqueck** [comment] 2022-01-28 16:15
Thanks for the feedback and the seed. Unfortunately If I remember correctly, @cypressfalls did use the latest version.

Since I can not reproduce it in my test setup either, I guess it is a race-condition. I pushed a change that might mitigate the problem in the next release

**Comment by cypressfalls** [comment] 2022-01-30 03:39
For what it's worth, I'd like to note that my mods in every world I play are ALWAYS up to date, because for 1.18 since all the mods are new, I check for updates every single time I log on & make a backup if anything changes. This is with the most recent versions of everything.

**Comment by quiqueck** [comment] 2022-02-04 16:45
Could you please try again with 1.0.2 and report back to us if the problem still persists?

**Comment by cypressfalls** [comment] 2022-02-14 21:31
Hi! Sorry, testing that now<3 All mods listed in my old post are once again up to date:)

After backing up the world and going to the end to see if the problem persisted, I've found that it seems to be running okay right now. Will report back later if it crashes again.

Attached is screenshots from our chunks corrupting and then reloading with what it assumed to be the correct biomes - not a problem for us, but it is progress in that the chunks seem to be loading fine now even if cosmetically they messed up.
![2022-02-14_16 29 28](https://user-images.githubusercontent.com/98366118/153949668-d3395d5b-0d9d-4f37-be72-e85cb1b24650.png)
![2022-02-14_16 29 11](https://user-images.githubusercontent.com/98366118/153949682-6d9c5fea-f7a5-4bf7-bc0a-2f0e2a900f13.png)
![2022-02-14_16 29 09](https://user-images.githubusercontent.com/98366118/153949705-ae763901-965c-4624-ac6d-0ab43afed00a.png)
![2022-02-14_16 31 25](https://user-images.githubusercontent.com/98366118/153949796-b9fec358-8ee1-4a6f-b1b5-90f6dfda5a95.png)

**Closed** 2022-03-07 13:20 UTC
Labels: bug, question
