### ISSUE TITLE
logs explode with dash loader.

### ISSUE THREAD

**Issue by jklw10** [paulevsGitch/BetterEnd#298] opened 2021-08-31 15:11 UTC
![image](https://user-images.githubusercontent.com/8884828/131528229-6f5ed938-0882-4627-bd2f-281978462e0c.png)
i'll post the full logs if needed but i'm still trying to see if i can even launch the game.

**Comment by Fireface677** [comment] 2021-08-31 15:12
Dash loader is incompatible.

**Comment by jklw10** [comment] 2021-08-31 15:13
is there a way you could fix this on your side or is it more feasible for dashloader?

**Comment by Fireface677** [comment] 2021-08-31 15:15
The problem is on their side
![image](https://user-images.githubusercontent.com/62745466/131529149-a7e08ef3-8ffa-4c4e-8fca-285a3dbd3f6c.png)

**Comment by jklw10** [comment] 2021-08-31 15:15
ah i see it's marked as a wont fix. thanks anyways. i'll see if someone on dashloaders side is able to do something about this.

**Comment by jklw10** [comment] 2021-08-31 15:16
actually it seems opening is possible just very slow. for the first time.

**Comment by Fireface677** [comment] 2021-08-31 15:19
yes

**Comment by paulevsGitch** [comment] 2021-08-31 16:04
Duplicate of #289

**Closed by paulevsGitch** 2021-08-31 16:04 UTC
