### ISSUE TITLE
Wrong Client side block rendering!

### ISSUE THREAD

**Issue by OverTasked** [paulevsGitch/BetterEnd#275] opened 2021-08-08 06:55 UTC
Hi guys, 
I am trying to run a modded Fabric serer with these mods:
![image](https://user-images.githubusercontent.com/88609269/128623588-58ad130f-df8a-484d-80e5-b129e59ce15e.png)
It renders , for example, waterlogged shulk censors instead of andesite, and cake with candles instead of granite
See Images here: 
![image](https://user-images.githubusercontent.com/88609269/128623684-8816617f-6058-44d9-a32c-76268b768ecf.png)
![image](https://user-images.githubusercontent.com/88609269/128623698-4eebee54-4401-4ea4-a647-60b57169edcb.png)
![image](https://user-images.githubusercontent.com/88609269/128623714-5cf6c5df-7e14-4dcc-83b5-88488b6c0d6d.png)

Thanks and hope you guys get a fix.

**Comment by paulevsGitch** [comment] 2021-08-08 09:01
Your mods and configs on client are not identical to server ones

**Comment by paulevsGitch** [comment] 2021-08-08 09:04
Duplicate of #49

**Closed by paulevsGitch** 2021-08-08 09:04 UTC
