### ISSUE TITLE
Better End crashes when attempting to generate terrain beyond main island

### ISSUE THREAD

**Issue by yojakeo** [paulevsGitch/BetterEnd#202] opened 2021-06-08 04:25 UTC
Here's my crash log: https://gist.githubusercontent.com/natanfudge/d676c8d19f325e7baad14d02e4cd519b/raw/de56fb092301fe1a5f316801faa0ca8dc224c642/crash.txt

I'm using a modified version of the "Fabulously Optimized" modpack for 1.16.5... I have a experimental version of Sodium that's compatible with Immersive Portals. The rest of the mods don't touch the end so theoretically they should cause no issue.

It's not an issue with Hydrogen (I saw this mentioned) as I don't have that mod, and I checked the level.dat and the correct generation is being used.

From the crash log it seems like Better End's cave gen is causing the crash? I'm not great on reading Java stack trace.

**Comment by paulevsGitch** [comment] 2021-06-08 06:49
Duplicate of #154 - remove Hydrogen, it is not compatible at this moment

**Closed by paulevsGitch** 2021-06-08 06:49 UTC
