### ISSUE TITLE
Fog is still present even when it's disabled using the No Fog mod

### ISSUE THREAD

**Issue by KB-Q** [paulevsGitch/BetterEnd#432] opened 2022-02-05 11:50 UTC
Please see the attached screenshot. As you can see the fog is still present even when all fog was disabled using the No Fog mod. Game version is 1.18.1 (using fabric). Using the latest version of Better End. 

Similar issue present in the Better Nether mod also... so if there's a simple fix for both of these mods please let me know. Thanks in advance.

![2022-02-05_17 18 14](https://user-images.githubusercontent.com/59303688/152640882-51a7bae9-6e81-4120-96d1-cc1d216ca0ba.png)

**Comment by paulevsGitch** [comment] 2022-02-05 14:53
Duplicate of https://github.com/paulevsGitch/BCLib/issues/74

**Closed by paulevsGitch** 2022-02-05 14:53 UTC
