### ISSUE TITLE
I kill the dragon, the game crashes

### ISSUE THREAD

**Issue by AndGar03** [paulevsGitch/BetterEnd#172] opened 2021-05-11 20:22 UTC
[crash-2021-05-11_15.19.46-client.txt](https://github.com/paulevsGitch/BetterEnd/files/6461788/crash-2021-05-11_15.19.46-client.txt)

I tried to kill the dragon and the game crashes

**Comment by paulevsGitch** [comment] 2021-05-12 14:36
Looks like duplicate of #23

**Comment by paulevsGitch** [comment] 2021-05-12 14:37
Issue is on Extreme Sound Muffler, all possible fixes from our side are already implemented

**Closed by paulevsGitch** 2021-05-12 14:37 UTC
