### ISSUE TITLE
Each time i kill the Drake, a new Portals gets formed...

### ISSUE THREAD

**Issue by Anti27** [paulevsGitch/BetterEnd#347] opened 2021-11-16 02:44 UTC
https://i.imgur.com/Riu2DEl.png
1.17.1, fabric, just another modpack 2.9.2b, better-end-0.11.0-pre.jar

**Comment by paulevsGitch** [comment] 2021-11-21 04:45
Duplicate of old issues, looks like sometimes file cannot be readed properly or there is an issue in code that are not triggered on each time

**Comment by paulevsGitch** [comment] 2021-11-30 12:27
Fixed in 0.12.5

**Closed by paulevsGitch** 2021-11-30 12:27 UTC
Labels: bug, in dev code
