### ISSUE TITLE
Mixin Apply Failure

### ISSUE THREAD

**Issue by TheIrishStud** [paulevsGitch/BetterEnd#377] opened 2021-12-30 18:25 UTC
https://pastebin.com/StiXfEQB

**Comment by paulevsGitch** [comment] 2021-12-30 19:58
Looks like one of your mods changes NoiseBasedChunkGenerator (probably replaces it with a custom one)

**Comment by paulevsGitch** [comment] 2021-12-30 20:01
Wait, it is a duplicate of #378

**Closed by paulevsGitch** 2021-12-30 20:01 UTC
