### ISSUE TITLE
BetterEnd crash client when load end

### ISSUE THREAD

**Issue by schuberty** [paulevsGitch/BetterEnd#244] opened 2021-07-13 18:20 UTC
I have a server with Fabric 0.11.6 at Minecraft 1.17.

I downloaded the BetterEnd but when I put all the ender eyes it crashes my client, but the server stays ok.

Here's the log of the client. Don't know if it incompatible with any other mod or something. If I take BCLib and BetterEnd it works fine.

[2021-07-13-4.log](https://github.com/paulevsGitch/BetterEnd/files/6811102/2021-07-13-4.log)

**Comment by paulevsGitch** [comment] 2021-07-13 19:03
Looks like something breaks model loading process, there are also API and library duplication warnings. Probably one of your mods breaks mode loading. There are also sky rendering conflicts:

![image](https://user-images.githubusercontent.com/17707380/125510221-c7fa111e-1064-40d9-892a-09bdee1c1760.png)

**Comment by schuberty** [comment] 2021-07-13 19:14
If it is about render/model maybe it is Immersive Portals.

Thanks!

**Comment by paulevsGitch** [comment] 2021-07-13 19:22
The issue is the same as #243 and #241

**Comment by schuberty** [comment] 2021-07-15 20:42
I removed everything from [qouteall](https://github.com/qouteall), mainly the [immersive portal](https://github.com/qouteall/ImmersivePortalsMod), and it works now. Do you know if it is something dealing with mixins?

Or if there's any other way that I might help?

I really like both mods so I wish there was a way of making them compatible.

BetterNether doesn't seen to have any issues but maybe is because it doesn't use BCLib yet.

**Comment by paulevsGitch** [comment] 2021-07-15 22:10
You probably have same issue as #247, so I'm closing this

**Closed by paulevsGitch** 2021-07-15 22:10 UTC
Labels: external problem
