### ISSUE TITLE
Extreme levels of server corruption

### ISSUE THREAD

**Issue by Alexgamingyz** [paulevsGitch/BetterEnd#187] opened 2021-05-24 18:39 UTC
I usually play minecraft on my fabric version (1.16.5 fabric), on single player worlds this works perfectly fine, but when i join a server it is gonna make random blocks into other random blocks. 
(Example: random blocks of air is transformed into waterlogged tube coral, shulkerboxes are transformed into command blocks, netherite blocks into target blocks, etc the list goes on).

i do know that it will not add the new biomes of the end into servers, but i still keep it in the loader so that if i go from a server to my singleplayer world(s) i dont need to exit and go back in minecraft. it is very annoying to join a server and have my house be transformed into random glazed terracotas or random blocks. (and yes it includes waterlogged versions of blocks, unwaterlogged, front facing doors, top/bottom slabs)

**Comment by paulevsGitch** [comment] 2021-05-25 00:05
Duplicate of #178 and #49. The mod is not designed to be used on client-side on unmodded servers

**Closed by paulevsGitch** 2021-05-25 00:05 UTC
