### ISSUE TITLE
Kubejs won't remove recipes OR hide in REI

### ISSUE THREAD

**Issue by Dejeh** [paulevsGitch/BetterEnd#353] opened 2021-11-19 23:47 UTC
Betterend: 0.12.2-1.17.1
Kubejs: 1.17 alpha

I thought it might be Kubejs error but it removes recipe from other mods/vanilla fine.
Since there's no Betterend config option to remove barrels or other woodblock, I tried using Kubejs. Example in server-scripts:
onEvent('recipes', event => {
        event.remove({output: 'betterend:lucernia_barrel'})
})
I also tried doing it by id, but it would not remove the recipe in-game.

Hiding better end items from REI doesn't work in client-scripts, example:
onEvent('rei.hide.items', event => {
        event.hide('betterend:lucernia_barrel')
})

**/reload stops REI from showing recipes for better end**, but after restarting and searching for lucernia barrel, it's still there.

One last thing: setting a recipe to false in better end config does not actually remove its recipe, it only works when you set it to false in blocks/items as well? What going on :(

**Comment by paulevsGitch** [comment] 2021-11-20 09:52
BetterEnd has a config to disable any recipe. KubeJS has compatibility issues that were fixed some time ago, but probably will require fixes again

**Comment by paulevsGitch** [comment] 2021-11-21 04:24
Duplicate of #338

**Closed by paulevsGitch** 2021-11-21 04:24 UTC
