### ISSUE TITLE
New Elytras not working 

### ISSUE THREAD

**Issue by Rayonlio** [paulevsGitch/BetterEnd#341] opened 2021-11-05 21:02 UTC
Hello !

I tried to use the new elytras on my server but it seems like they doesn't work, it's not possible to fly wearing them.

I created a new world to try again with the three different elytras, the vanilla one works but it's the same issue with the two others, here are the logs:
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/7488898/latest.log)

**Comment by paulevsGitch** [comment] 2021-11-05 21:45
Duplicate of #231

**Closed by paulevsGitch** 2021-11-05 21:45 UTC
