### ISSUE TITLE
[BUG] Overlapping Overworld Portal

### ISSUE THREAD

**Issue by Phoupraw** [paulevsGitch/BetterEnd#250] opened 2021-07-18 07:58 UTC
![2021-07-18_11 59 26](https://user-images.githubusercontent.com/50520903/126059607-862388b3-66f8-4ba7-9ce4-2f6e0e17500b.png)
The one above is activated while the one below isn't.
When I didn't kill the ender dragon, there was only one portal. When I killed the dragon, the portal above appeared.
I killed the dragon in another world, but this didn't happen again.

Version: 1.17.1 - 0.10.5
There is not any log except advancement appearing when the portal above appeared, so I don't upload the log.

**Comment by paulevsGitch** [comment] 2021-07-18 11:09
Duplicate of #245

**Closed by paulevsGitch** 2021-07-18 11:09 UTC
