### ISSUE TITLE
Fix Portal End stack up and have lost dragon egg

### ISSUE THREAD

**Issue by walkergod2411** [paulevsGitch/BetterEnd#306] opened 2021-09-11 10:29 UTC
![2021-09-10_23 27 00](https://user-images.githubusercontent.com/70162238/132944832-8d09438c-1a63-4493-8446-ae0258840cd5.png)

**Comment by paulevsGitch** [comment] 2021-09-11 16:36
Duplicate of #245

**Closed by paulevsGitch** 2021-09-11 16:36 UTC
