### ISSUE TITLE
BetterEnd 0.11.0 Textures Missing

### ISSUE THREAD

**Issue by windowslogic** [paulevsGitch/BetterEnd#282] opened 2021-08-11 19:56 UTC
Updated to BetterEnd 0.11.0 and most of the textures are missing or bugged.

**Comment by paulevsGitch** [comment] 2021-08-11 20:01
Probably duplicate of [this issue](https://github.com/paulevsGitch/BCLib/issues/31)

**Closed** 2021-08-11 20:01 UTC
