### ISSUE TITLE
[Bug] Smelting recipes are not working (except mod smelter)

### ISSUE THREAD

**Issue by Ryztiq** [paulevsGitch/BetterEnd#389] opened 2022-01-06 00:38 UTC
Tried in both multiplayer and singleplayer, nothing can be smelted in any type of smelter or furnace.

**Comment by Hideout28** [comment] 2022-01-06 23:20
Did you make sure that in the end furnace with both slots filled you used either Coal Blocks, Lava Buckets, or Blaze Rods as fuel? Normal fuels like wood or individual pieces of coal don't work in it.

**Comment by paulevsGitch** [comment] 2022-01-06 23:54
> Did you make sure that in the end furnace with both slots filled you used either Coal Blocks, Lava Buckets, or Blaze Rods as fuel? Normal fuels like wood or individual pieces of coal don't work in it.

The issue is about normal Furnace & Smelter recipes, not about End Stone Smelter recipes

**Comment by Theobot3782** [comment] 2022-01-10 21:33
The anvil recipes don't work either!!! I LOVE AETERNIUM!!! :}

**Comment by Theobot3782** [comment] 2022-01-10 21:33
AND BESKAR!!!

**Comment by paulevsGitch** [comment] 2022-01-11 02:17
@Theobot3782, if you continue to place caps in any message that you post and continue conversation on closed issues - I will block you

**Comment by paulevsGitch** [comment] 2022-01-13 13:02
Fixed in BCLib 1.2.3

**Closed by paulevsGitch** 2022-01-13 13:02 UTC
Labels: bug
