### ISSUE TITLE
Crystalite Armor's Regen effect doesn't work as intended

### ISSUE THREAD

**Issue by LifeWatcher123** [paulevsGitch/BetterEnd#273] opened 2021-08-06 03:40 UTC
### Issue and Steps to Reproduce
While wearing the Crystalite Armor set, its regen effect doesn't seem to work. The other status effects that the armor pieces give seem to work just fine.

To reproduce:

1. Create a new Minecraft 1.17.1 instance
2. Install Fabric Loader, BetterEnd, and dependencies
3. Create a new world
4. Take damage until at half-health and unsufficient hunger to disable natural regeneration
5. Wear Crystalite Armor set.

#### Versions
 - Minecraft Version: 1.17.1
 - Fabric Loader 0.11.6
 - bclib-0.2.4
 - better-end-0.10.5-pre
 - fabric-api-0.37.1+1.17

#### Expected
The player should be gaining health.

#### Actual
The player isn't gaining health.

### Additional Details
* Regeneration from other sources (e.i. from potions, /effect commands, etc.) works normally. I'm guessing it's the duration of the regen effect given by the armor that is causing the bug. 
* I would've tried to fix it myself, but I'm not familiar with the `net.minecraft.*` package, so I have no idea where to start.

**Comment by paulevsGitch** [comment] 2021-08-06 06:57
Duplicate of #262

**Closed by paulevsGitch** 2021-08-06 06:57 UTC
